//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusGym.Exceptions.Equipamentos {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EquipamentoExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EquipamentoExceptions() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexusGym.Exceptions.Equipamentos.EquipamentoExceptions", typeof(EquipamentoExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Equipamento foi ativo.
        /// </summary>
        public static string Equipamento_Ativo {
            get {
                return ResourceManager.GetString("Equipamento_Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Equipamento foi inativado.
        /// </summary>
        public static string Equipamento_Inativo {
            get {
                return ResourceManager.GetString("Equipamento_Inativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Equipamento ja esta ativo.
        /// </summary>
        public static string Equipamento_JaAtivo {
            get {
                return ResourceManager.GetString("Equipamento_JaAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Equipamento ja esta inativo
        ///.
        /// </summary>
        public static string Equipamento_JaInativo {
            get {
                return ResourceManager.GetString("Equipamento_JaInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A marca do equipamento é obrigatória.
        /// </summary>
        public static string Equipamento_MarcaObrigatorio {
            get {
                return ResourceManager.GetString("Equipamento_MarcaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Equipamento não foi encontrado.
        /// </summary>
        public static string Equipamento_NaoEncontrado {
            get {
                return ResourceManager.GetString("Equipamento_NaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O nome do equipamento é obrigatório
        ///.
        /// </summary>
        public static string Equipamento_NomeObrigatorio {
            get {
                return ResourceManager.GetString("Equipamento_NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Peso do equipamento é obrigatório
        ///.
        /// </summary>
        public static string Equipamento_PesoObrigatorio {
            get {
                return ResourceManager.GetString("Equipamento_PesoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Plano foi ativado com sucesso.
        /// </summary>
        public static string Plano_Ativo {
            get {
                return ResourceManager.GetString("Plano_Ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Plano foi inativado com sucesso.
        /// </summary>
        public static string Plano_Inativo {
            get {
                return ResourceManager.GetString("Plano_Inativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O plano ja está ativo.
        /// </summary>
        public static string Plano_JaAtivo {
            get {
                return ResourceManager.GetString("Plano_JaAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Plano já está inativo.
        /// </summary>
        public static string Plano_JaInativo {
            get {
                return ResourceManager.GetString("Plano_JaInativo", resourceCulture);
            }
        }
    }
}
