//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusGym.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionsMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionsMessage() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexusGym.Exceptions.ExceptionsMessage", typeof(ExceptionsMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Cliente está ativo !.
        /// </summary>
        public static string ClienteAtivo {
            get {
                return ResourceManager.GetString("ClienteAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Cliente está Inativo !.
        /// </summary>
        public static string ClienteInativo {
            get {
                return ResourceManager.GetString("ClienteInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O cliente é obrigatório !.
        /// </summary>
        public static string ClienteObrigatório {
            get {
                return ResourceManager.GetString("ClienteObrigatório", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esse cliente ja possui um plano ativo !.
        /// </summary>
        public static string ClientePossuiPlano {
            get {
                return ResourceManager.GetString("ClientePossuiPlano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ja existe uma pessoa com esse CPF cadastrado !.
        /// </summary>
        public static string CpfExiste {
            get {
                return ResourceManager.GetString("CpfExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Descricao é obrigatória.
        /// </summary>
        public static string DescricaoObrigatoria {
            get {
                return ResourceManager.GetString("DescricaoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Duração é obrigatória !.
        /// </summary>
        public static string DuracaoObrigatoria {
            get {
                return ResourceManager.GetString("DuracaoObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Email é obrigatório !.
        /// </summary>
        public static string EmailObrigatorio {
            get {
                return ResourceManager.GetString("EmailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Endereço é obrigatório !.
        /// </summary>
        public static string EnderecoObrigatorio {
            get {
                return ResourceManager.GetString("EnderecoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Equipamento está ativo !.
        /// </summary>
        public static string EquipamentoAtivo {
            get {
                return ResourceManager.GetString("EquipamentoAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Equipamento está Inativo !.
        /// </summary>
        public static string EquipamentoInativo {
            get {
                return ResourceManager.GetString("EquipamentoInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Marca é obrigatória !.
        /// </summary>
        public static string MarcaObrigatoria {
            get {
                return ResourceManager.GetString("MarcaObrigatoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Nome é obrigatório !.
        /// </summary>
        public static string NomeObrigatorio {
            get {
                return ResourceManager.GetString("NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Peso é obrigatório !.
        /// </summary>
        public static string PesoObrigatorio {
            get {
                return ResourceManager.GetString("PesoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Plano está ativo.
        /// </summary>
        public static string PlanoAtivado {
            get {
                return ResourceManager.GetString("PlanoAtivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Plano esta inativado.
        /// </summary>
        public static string PlanoInativado {
            get {
                return ResourceManager.GetString("PlanoInativado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Plano já esta vinculado ao cliente.
        /// </summary>
        public static string PlanoJaVinculadoAoCliente {
            get {
                return ResourceManager.GetString("PlanoJaVinculadoAoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Plano é obrigatório !.
        /// </summary>
        public static string PlanoObrigatorio {
            get {
                return ResourceManager.GetString("PlanoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O telefone é obrigatório !.
        /// </summary>
        public static string TelefoneObrigatorio {
            get {
                return ResourceManager.GetString("TelefoneObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Valor é obrigatório !.
        /// </summary>
        public static string ValorObrigatorio {
            get {
                return ResourceManager.GetString("ValorObrigatorio", resourceCulture);
            }
        }
    }
}
